---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ndk-dashboard
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ndk-dashboard-reader
rules:
  # Allow full management of NDK custom resources
  - apiGroups: ["dataservices.nutanix.com"]
    resources:
      - applications
      - applicationsnapshots
      - applicationrestores
      - storageclusters
      - protectionplans
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Allow reading pods and namespaces for context
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ndk-dashboard-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ndk-dashboard-reader
subjects:
  - kind: ServiceAccount
    name: ndk-dashboard
    namespace: default