---
apiVersion: v1
kind: Secret
metadata:
  name: ndk-dashboard-secret
  namespace: default
type: Opaque
stringData:
  # Change these values for production!
  SECRET_KEY: "change-this-to-a-random-secret-key-in-production"
  DASHBOARD_USERNAME: "admin"
  DASHBOARD_PASSWORD: "admin"